grpc-port: 50052
database:
  driver: mysql
  debug: false
  source-name: "root:root@tcp(127.0.0.1:3306)/rent-house-crawler?loc=Local&parseTime=True"
cache:
  driver: redis
  addr: 127.0.0.1:6379
  tls: false
  tls-skip-verify: false
  password: ""
  db: 0
crawlers:
  "591":
    cache: false
    proxy: true
    cookie-and-csrf-token-url: ""
    urls:
      - ""
    detail-cookie-token-key: ""
    detail-data-url: ""
    detail-url: ""
jobs:
  update-591-homes: "0 0 * * *"

