// Code generated by ent, DO NOT EDIT.

package rent591homedetailpositionround

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldTitle, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldKey, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldActive, v))
}

// CommunityName applies equality check predicate on the "community_name" field. It's identical to CommunityNameEQ.
func CommunityName(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldCommunityName, v))
}

// CommunityID applies equality check predicate on the "community_id" field. It's identical to CommunityIDEQ.
func CommunityID(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldCommunityID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldAddress, v))
}

// Lat applies equality check predicate on the "lat" field. It's identical to LatEQ.
func Lat(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldLat, v))
}

// Lng applies equality check predicate on the "lng" field. It's identical to LngEQ.
func Lng(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldLng, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContainsFold(FieldTitle, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContainsFold(FieldKey, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldActive, v))
}

// ActiveIn applies the In predicate on the "active" field.
func ActiveIn(vs ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldActive, vs...))
}

// ActiveNotIn applies the NotIn predicate on the "active" field.
func ActiveNotIn(vs ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldActive, vs...))
}

// ActiveGT applies the GT predicate on the "active" field.
func ActiveGT(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldActive, v))
}

// ActiveGTE applies the GTE predicate on the "active" field.
func ActiveGTE(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldActive, v))
}

// ActiveLT applies the LT predicate on the "active" field.
func ActiveLT(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldActive, v))
}

// ActiveLTE applies the LTE predicate on the "active" field.
func ActiveLTE(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldActive, v))
}

// CommunityNameEQ applies the EQ predicate on the "community_name" field.
func CommunityNameEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldCommunityName, v))
}

// CommunityNameNEQ applies the NEQ predicate on the "community_name" field.
func CommunityNameNEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldCommunityName, v))
}

// CommunityNameIn applies the In predicate on the "community_name" field.
func CommunityNameIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldCommunityName, vs...))
}

// CommunityNameNotIn applies the NotIn predicate on the "community_name" field.
func CommunityNameNotIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldCommunityName, vs...))
}

// CommunityNameGT applies the GT predicate on the "community_name" field.
func CommunityNameGT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldCommunityName, v))
}

// CommunityNameGTE applies the GTE predicate on the "community_name" field.
func CommunityNameGTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldCommunityName, v))
}

// CommunityNameLT applies the LT predicate on the "community_name" field.
func CommunityNameLT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldCommunityName, v))
}

// CommunityNameLTE applies the LTE predicate on the "community_name" field.
func CommunityNameLTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldCommunityName, v))
}

// CommunityNameContains applies the Contains predicate on the "community_name" field.
func CommunityNameContains(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContains(FieldCommunityName, v))
}

// CommunityNameHasPrefix applies the HasPrefix predicate on the "community_name" field.
func CommunityNameHasPrefix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasPrefix(FieldCommunityName, v))
}

// CommunityNameHasSuffix applies the HasSuffix predicate on the "community_name" field.
func CommunityNameHasSuffix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasSuffix(FieldCommunityName, v))
}

// CommunityNameEqualFold applies the EqualFold predicate on the "community_name" field.
func CommunityNameEqualFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEqualFold(FieldCommunityName, v))
}

// CommunityNameContainsFold applies the ContainsFold predicate on the "community_name" field.
func CommunityNameContainsFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContainsFold(FieldCommunityName, v))
}

// CommunityIDEQ applies the EQ predicate on the "community_id" field.
func CommunityIDEQ(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldCommunityID, v))
}

// CommunityIDNEQ applies the NEQ predicate on the "community_id" field.
func CommunityIDNEQ(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldCommunityID, v))
}

// CommunityIDIn applies the In predicate on the "community_id" field.
func CommunityIDIn(vs ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldCommunityID, vs...))
}

// CommunityIDNotIn applies the NotIn predicate on the "community_id" field.
func CommunityIDNotIn(vs ...int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldCommunityID, vs...))
}

// CommunityIDGT applies the GT predicate on the "community_id" field.
func CommunityIDGT(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldCommunityID, v))
}

// CommunityIDGTE applies the GTE predicate on the "community_id" field.
func CommunityIDGTE(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldCommunityID, v))
}

// CommunityIDLT applies the LT predicate on the "community_id" field.
func CommunityIDLT(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldCommunityID, v))
}

// CommunityIDLTE applies the LTE predicate on the "community_id" field.
func CommunityIDLTE(v int) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldCommunityID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldContainsFold(FieldAddress, v))
}

// LatEQ applies the EQ predicate on the "lat" field.
func LatEQ(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldLat, v))
}

// LatNEQ applies the NEQ predicate on the "lat" field.
func LatNEQ(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldLat, v))
}

// LatIn applies the In predicate on the "lat" field.
func LatIn(vs ...float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldLat, vs...))
}

// LatNotIn applies the NotIn predicate on the "lat" field.
func LatNotIn(vs ...float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldLat, vs...))
}

// LatGT applies the GT predicate on the "lat" field.
func LatGT(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldLat, v))
}

// LatGTE applies the GTE predicate on the "lat" field.
func LatGTE(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldLat, v))
}

// LatLT applies the LT predicate on the "lat" field.
func LatLT(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldLat, v))
}

// LatLTE applies the LTE predicate on the "lat" field.
func LatLTE(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldLat, v))
}

// LngEQ applies the EQ predicate on the "lng" field.
func LngEQ(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldEQ(FieldLng, v))
}

// LngNEQ applies the NEQ predicate on the "lng" field.
func LngNEQ(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNEQ(FieldLng, v))
}

// LngIn applies the In predicate on the "lng" field.
func LngIn(vs ...float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldIn(FieldLng, vs...))
}

// LngNotIn applies the NotIn predicate on the "lng" field.
func LngNotIn(vs ...float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldNotIn(FieldLng, vs...))
}

// LngGT applies the GT predicate on the "lng" field.
func LngGT(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGT(FieldLng, v))
}

// LngGTE applies the GTE predicate on the "lng" field.
func LngGTE(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldGTE(FieldLng, v))
}

// LngLT applies the LT predicate on the "lng" field.
func LngLT(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLT(FieldLng, v))
}

// LngLTE applies the LTE predicate on the "lng" field.
func LngLTE(v float64) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(sql.FieldLTE(FieldLng, v))
}

// HasRent591homeDetails applies the HasEdge predicate on the "rent591home_details" edge.
func HasRent591homeDetails() predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, Rent591homeDetailsTable, Rent591homeDetailsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRent591homeDetailsWith applies the HasEdge predicate on the "rent591home_details" edge with a given conditions (other predicates).
func HasRent591homeDetailsWith(preds ...predicate.Rent591HomeDetail) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		step := newRent591homeDetailsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRent591homeDetailPositionRoundDatas applies the HasEdge predicate on the "rent591home_detail_position_round_datas" edge.
func HasRent591homeDetailPositionRoundDatas() predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, Rent591homeDetailPositionRoundDatasTable, Rent591homeDetailPositionRoundDatasPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRent591homeDetailPositionRoundDatasWith applies the HasEdge predicate on the "rent591home_detail_position_round_datas" edge with a given conditions (other predicates).
func HasRent591homeDetailPositionRoundDatasWith(preds ...predicate.Rent591HomeDetailPositionRoundData) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		step := newRent591homeDetailPositionRoundDatasStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Rent591HomeDetailPositionRound) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Rent591HomeDetailPositionRound) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Rent591HomeDetailPositionRound) predicate.Rent591HomeDetailPositionRound {
	return predicate.Rent591HomeDetailPositionRound(func(s *sql.Selector) {
		p(s.Not())
	})
}
