// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetail"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailbreadcrumb"
)

// Rent591HomeDetailBreadcrumbCreate is the builder for creating a Rent591HomeDetailBreadcrumb entity.
type Rent591HomeDetailBreadcrumbCreate struct {
	config
	mutation *Rent591HomeDetailBreadcrumbMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) SetName(s string) *Rent591HomeDetailBreadcrumbCreate {
	rdbc.mutation.SetName(s)
	return rdbc
}

// SetPostID sets the "post_id" field.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) SetPostID(i int) *Rent591HomeDetailBreadcrumbCreate {
	rdbc.mutation.SetPostID(i)
	return rdbc
}

// SetQuery sets the "query" field.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) SetQuery(s string) *Rent591HomeDetailBreadcrumbCreate {
	rdbc.mutation.SetQuery(s)
	return rdbc
}

// SetLink sets the "link" field.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) SetLink(s string) *Rent591HomeDetailBreadcrumbCreate {
	rdbc.mutation.SetLink(s)
	return rdbc
}

// AddRent591homeDetailIDs adds the "rent591home_details" edge to the Rent591HomeDetail entity by IDs.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) AddRent591homeDetailIDs(ids ...int) *Rent591HomeDetailBreadcrumbCreate {
	rdbc.mutation.AddRent591homeDetailIDs(ids...)
	return rdbc
}

// AddRent591homeDetails adds the "rent591home_details" edges to the Rent591HomeDetail entity.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) AddRent591homeDetails(r ...*Rent591HomeDetail) *Rent591HomeDetailBreadcrumbCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rdbc.AddRent591homeDetailIDs(ids...)
}

// Mutation returns the Rent591HomeDetailBreadcrumbMutation object of the builder.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) Mutation() *Rent591HomeDetailBreadcrumbMutation {
	return rdbc.mutation
}

// Save creates the Rent591HomeDetailBreadcrumb in the database.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) Save(ctx context.Context) (*Rent591HomeDetailBreadcrumb, error) {
	return withHooks(ctx, rdbc.sqlSave, rdbc.mutation, rdbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) SaveX(ctx context.Context) *Rent591HomeDetailBreadcrumb {
	v, err := rdbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) Exec(ctx context.Context) error {
	_, err := rdbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) ExecX(ctx context.Context) {
	if err := rdbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rdbc *Rent591HomeDetailBreadcrumbCreate) check() error {
	if _, ok := rdbc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Rent591HomeDetailBreadcrumb.name"`)}
	}
	if _, ok := rdbc.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "Rent591HomeDetailBreadcrumb.post_id"`)}
	}
	if _, ok := rdbc.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "Rent591HomeDetailBreadcrumb.query"`)}
	}
	if _, ok := rdbc.mutation.Link(); !ok {
		return &ValidationError{Name: "link", err: errors.New(`ent: missing required field "Rent591HomeDetailBreadcrumb.link"`)}
	}
	return nil
}

func (rdbc *Rent591HomeDetailBreadcrumbCreate) sqlSave(ctx context.Context) (*Rent591HomeDetailBreadcrumb, error) {
	if err := rdbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rdbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rdbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rdbc.mutation.id = &_node.ID
	rdbc.mutation.done = true
	return _node, nil
}

func (rdbc *Rent591HomeDetailBreadcrumbCreate) createSpec() (*Rent591HomeDetailBreadcrumb, *sqlgraph.CreateSpec) {
	var (
		_node = &Rent591HomeDetailBreadcrumb{config: rdbc.config}
		_spec = sqlgraph.NewCreateSpec(rent591homedetailbreadcrumb.Table, sqlgraph.NewFieldSpec(rent591homedetailbreadcrumb.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rdbc.conflict
	if value, ok := rdbc.mutation.Name(); ok {
		_spec.SetField(rent591homedetailbreadcrumb.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rdbc.mutation.PostID(); ok {
		_spec.SetField(rent591homedetailbreadcrumb.FieldPostID, field.TypeInt, value)
		_node.PostID = value
	}
	if value, ok := rdbc.mutation.Query(); ok {
		_spec.SetField(rent591homedetailbreadcrumb.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := rdbc.mutation.Link(); ok {
		_spec.SetField(rent591homedetailbreadcrumb.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if nodes := rdbc.mutation.Rent591homeDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   rent591homedetailbreadcrumb.Rent591homeDetailsTable,
			Columns: rent591homedetailbreadcrumb.Rent591homeDetailsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rent591homedetail.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Rent591HomeDetailBreadcrumbUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (rdbc *Rent591HomeDetailBreadcrumbCreate) OnConflict(opts ...sql.ConflictOption) *Rent591HomeDetailBreadcrumbUpsertOne {
	rdbc.conflict = opts
	return &Rent591HomeDetailBreadcrumbUpsertOne{
		create: rdbc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rdbc *Rent591HomeDetailBreadcrumbCreate) OnConflictColumns(columns ...string) *Rent591HomeDetailBreadcrumbUpsertOne {
	rdbc.conflict = append(rdbc.conflict, sql.ConflictColumns(columns...))
	return &Rent591HomeDetailBreadcrumbUpsertOne{
		create: rdbc,
	}
}

type (
	// Rent591HomeDetailBreadcrumbUpsertOne is the builder for "upsert"-ing
	//  one Rent591HomeDetailBreadcrumb node.
	Rent591HomeDetailBreadcrumbUpsertOne struct {
		create *Rent591HomeDetailBreadcrumbCreate
	}

	// Rent591HomeDetailBreadcrumbUpsert is the "OnConflict" setter.
	Rent591HomeDetailBreadcrumbUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *Rent591HomeDetailBreadcrumbUpsert) SetName(v string) *Rent591HomeDetailBreadcrumbUpsert {
	u.Set(rent591homedetailbreadcrumb.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsert) UpdateName() *Rent591HomeDetailBreadcrumbUpsert {
	u.SetExcluded(rent591homedetailbreadcrumb.FieldName)
	return u
}

// SetPostID sets the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsert) SetPostID(v int) *Rent591HomeDetailBreadcrumbUpsert {
	u.Set(rent591homedetailbreadcrumb.FieldPostID, v)
	return u
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsert) UpdatePostID() *Rent591HomeDetailBreadcrumbUpsert {
	u.SetExcluded(rent591homedetailbreadcrumb.FieldPostID)
	return u
}

// AddPostID adds v to the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsert) AddPostID(v int) *Rent591HomeDetailBreadcrumbUpsert {
	u.Add(rent591homedetailbreadcrumb.FieldPostID, v)
	return u
}

// SetQuery sets the "query" field.
func (u *Rent591HomeDetailBreadcrumbUpsert) SetQuery(v string) *Rent591HomeDetailBreadcrumbUpsert {
	u.Set(rent591homedetailbreadcrumb.FieldQuery, v)
	return u
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsert) UpdateQuery() *Rent591HomeDetailBreadcrumbUpsert {
	u.SetExcluded(rent591homedetailbreadcrumb.FieldQuery)
	return u
}

// SetLink sets the "link" field.
func (u *Rent591HomeDetailBreadcrumbUpsert) SetLink(v string) *Rent591HomeDetailBreadcrumbUpsert {
	u.Set(rent591homedetailbreadcrumb.FieldLink, v)
	return u
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsert) UpdateLink() *Rent591HomeDetailBreadcrumbUpsert {
	u.SetExcluded(rent591homedetailbreadcrumb.FieldLink)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Rent591HomeDetailBreadcrumbUpsertOne) UpdateNewValues() *Rent591HomeDetailBreadcrumbUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Rent591HomeDetailBreadcrumbUpsertOne) Ignore() *Rent591HomeDetailBreadcrumbUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) DoNothing() *Rent591HomeDetailBreadcrumbUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Rent591HomeDetailBreadcrumbCreate.OnConflict
// documentation for more info.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) Update(set func(*Rent591HomeDetailBreadcrumbUpsert)) *Rent591HomeDetailBreadcrumbUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Rent591HomeDetailBreadcrumbUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) SetName(v string) *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) UpdateName() *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateName()
	})
}

// SetPostID sets the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) SetPostID(v int) *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) AddPostID(v int) *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) UpdatePostID() *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdatePostID()
	})
}

// SetQuery sets the "query" field.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) SetQuery(v string) *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) UpdateQuery() *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateQuery()
	})
}

// SetLink sets the "link" field.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) SetLink(v string) *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) UpdateLink() *Rent591HomeDetailBreadcrumbUpsertOne {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateLink()
	})
}

// Exec executes the query.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Rent591HomeDetailBreadcrumbCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Rent591HomeDetailBreadcrumbUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Rent591HomeDetailBreadcrumbCreateBulk is the builder for creating many Rent591HomeDetailBreadcrumb entities in bulk.
type Rent591HomeDetailBreadcrumbCreateBulk struct {
	config
	builders []*Rent591HomeDetailBreadcrumbCreate
	conflict []sql.ConflictOption
}

// Save creates the Rent591HomeDetailBreadcrumb entities in the database.
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) Save(ctx context.Context) ([]*Rent591HomeDetailBreadcrumb, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rdbcb.builders))
	nodes := make([]*Rent591HomeDetailBreadcrumb, len(rdbcb.builders))
	mutators := make([]Mutator, len(rdbcb.builders))
	for i := range rdbcb.builders {
		func(i int, root context.Context) {
			builder := rdbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Rent591HomeDetailBreadcrumbMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rdbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rdbcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rdbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rdbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) SaveX(ctx context.Context) []*Rent591HomeDetailBreadcrumb {
	v, err := rdbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) Exec(ctx context.Context) error {
	_, err := rdbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) ExecX(ctx context.Context) {
	if err := rdbcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rent591HomeDetailBreadcrumb.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Rent591HomeDetailBreadcrumbUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) OnConflict(opts ...sql.ConflictOption) *Rent591HomeDetailBreadcrumbUpsertBulk {
	rdbcb.conflict = opts
	return &Rent591HomeDetailBreadcrumbUpsertBulk{
		create: rdbcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rdbcb *Rent591HomeDetailBreadcrumbCreateBulk) OnConflictColumns(columns ...string) *Rent591HomeDetailBreadcrumbUpsertBulk {
	rdbcb.conflict = append(rdbcb.conflict, sql.ConflictColumns(columns...))
	return &Rent591HomeDetailBreadcrumbUpsertBulk{
		create: rdbcb,
	}
}

// Rent591HomeDetailBreadcrumbUpsertBulk is the builder for "upsert"-ing
// a bulk of Rent591HomeDetailBreadcrumb nodes.
type Rent591HomeDetailBreadcrumbUpsertBulk struct {
	create *Rent591HomeDetailBreadcrumbCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) UpdateNewValues() *Rent591HomeDetailBreadcrumbUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailBreadcrumb.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) Ignore() *Rent591HomeDetailBreadcrumbUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) DoNothing() *Rent591HomeDetailBreadcrumbUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Rent591HomeDetailBreadcrumbCreateBulk.OnConflict
// documentation for more info.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) Update(set func(*Rent591HomeDetailBreadcrumbUpsert)) *Rent591HomeDetailBreadcrumbUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Rent591HomeDetailBreadcrumbUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) SetName(v string) *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) UpdateName() *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateName()
	})
}

// SetPostID sets the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) SetPostID(v int) *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetPostID(v)
	})
}

// AddPostID adds v to the "post_id" field.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) AddPostID(v int) *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.AddPostID(v)
	})
}

// UpdatePostID sets the "post_id" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) UpdatePostID() *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdatePostID()
	})
}

// SetQuery sets the "query" field.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) SetQuery(v string) *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetQuery(v)
	})
}

// UpdateQuery sets the "query" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) UpdateQuery() *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateQuery()
	})
}

// SetLink sets the "link" field.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) SetLink(v string) *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.SetLink(v)
	})
}

// UpdateLink sets the "link" field to the value that was provided on create.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) UpdateLink() *Rent591HomeDetailBreadcrumbUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailBreadcrumbUpsert) {
		s.UpdateLink()
	})
}

// Exec executes the query.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Rent591HomeDetailBreadcrumbCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Rent591HomeDetailBreadcrumbCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Rent591HomeDetailBreadcrumbUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
