// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591home"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetail"
	"github.com/programzheng/rent-house-crawler/ent/rent591homesurrounding"
	"github.com/programzheng/rent-house-crawler/ent/rent591hometag"
)

// Rent591HomeQuery is the builder for querying Rent591Home entities.
type Rent591HomeQuery struct {
	config
	ctx                         *QueryContext
	order                       []rent591home.OrderOption
	inters                      []Interceptor
	predicates                  []predicate.Rent591Home
	withRent591homeTags         *Rent591HomeTagQuery
	withRent591homeSurroundings *Rent591HomeSurroundingQuery
	withRent591homeDetails      *Rent591HomeDetailQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Rent591HomeQuery builder.
func (rq *Rent591HomeQuery) Where(ps ...predicate.Rent591Home) *Rent591HomeQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *Rent591HomeQuery) Limit(limit int) *Rent591HomeQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *Rent591HomeQuery) Offset(offset int) *Rent591HomeQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *Rent591HomeQuery) Unique(unique bool) *Rent591HomeQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *Rent591HomeQuery) Order(o ...rent591home.OrderOption) *Rent591HomeQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryRent591homeTags chains the current query on the "rent591home_tags" edge.
func (rq *Rent591HomeQuery) QueryRent591homeTags() *Rent591HomeTagQuery {
	query := (&Rent591HomeTagClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591home.Table, rent591home.FieldID, selector),
			sqlgraph.To(rent591hometag.Table, rent591hometag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, rent591home.Rent591homeTagsTable, rent591home.Rent591homeTagsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRent591homeSurroundings chains the current query on the "rent591home_surroundings" edge.
func (rq *Rent591HomeQuery) QueryRent591homeSurroundings() *Rent591HomeSurroundingQuery {
	query := (&Rent591HomeSurroundingClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591home.Table, rent591home.FieldID, selector),
			sqlgraph.To(rent591homesurrounding.Table, rent591homesurrounding.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, rent591home.Rent591homeSurroundingsTable, rent591home.Rent591homeSurroundingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRent591homeDetails chains the current query on the "rent591home_details" edge.
func (rq *Rent591HomeQuery) QueryRent591homeDetails() *Rent591HomeDetailQuery {
	query := (&Rent591HomeDetailClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591home.Table, rent591home.FieldID, selector),
			sqlgraph.To(rent591homedetail.Table, rent591homedetail.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, rent591home.Rent591homeDetailsTable, rent591home.Rent591homeDetailsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rent591Home entity from the query.
// Returns a *NotFoundError when no Rent591Home was found.
func (rq *Rent591HomeQuery) First(ctx context.Context) (*Rent591Home, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rent591home.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *Rent591HomeQuery) FirstX(ctx context.Context) *Rent591Home {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rent591Home ID from the query.
// Returns a *NotFoundError when no Rent591Home ID was found.
func (rq *Rent591HomeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rent591home.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *Rent591HomeQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rent591Home entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rent591Home entity is found.
// Returns a *NotFoundError when no Rent591Home entities are found.
func (rq *Rent591HomeQuery) Only(ctx context.Context) (*Rent591Home, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rent591home.Label}
	default:
		return nil, &NotSingularError{rent591home.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *Rent591HomeQuery) OnlyX(ctx context.Context) *Rent591Home {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rent591Home ID in the query.
// Returns a *NotSingularError when more than one Rent591Home ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *Rent591HomeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rent591home.Label}
	default:
		err = &NotSingularError{rent591home.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *Rent591HomeQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rent591Homes.
func (rq *Rent591HomeQuery) All(ctx context.Context) ([]*Rent591Home, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rent591Home, *Rent591HomeQuery]()
	return withInterceptors[[]*Rent591Home](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *Rent591HomeQuery) AllX(ctx context.Context) []*Rent591Home {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rent591Home IDs.
func (rq *Rent591HomeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(rent591home.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *Rent591HomeQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *Rent591HomeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*Rent591HomeQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *Rent591HomeQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *Rent591HomeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *Rent591HomeQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Rent591HomeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *Rent591HomeQuery) Clone() *Rent591HomeQuery {
	if rq == nil {
		return nil
	}
	return &Rent591HomeQuery{
		config:                      rq.config,
		ctx:                         rq.ctx.Clone(),
		order:                       append([]rent591home.OrderOption{}, rq.order...),
		inters:                      append([]Interceptor{}, rq.inters...),
		predicates:                  append([]predicate.Rent591Home{}, rq.predicates...),
		withRent591homeTags:         rq.withRent591homeTags.Clone(),
		withRent591homeSurroundings: rq.withRent591homeSurroundings.Clone(),
		withRent591homeDetails:      rq.withRent591homeDetails.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithRent591homeTags tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_tags" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *Rent591HomeQuery) WithRent591homeTags(opts ...func(*Rent591HomeTagQuery)) *Rent591HomeQuery {
	query := (&Rent591HomeTagClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRent591homeTags = query
	return rq
}

// WithRent591homeSurroundings tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_surroundings" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *Rent591HomeQuery) WithRent591homeSurroundings(opts ...func(*Rent591HomeSurroundingQuery)) *Rent591HomeQuery {
	query := (&Rent591HomeSurroundingClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRent591homeSurroundings = query
	return rq
}

// WithRent591homeDetails tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_details" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *Rent591HomeQuery) WithRent591homeDetails(opts ...func(*Rent591HomeDetailQuery)) *Rent591HomeQuery {
	query := (&Rent591HomeDetailClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withRent591homeDetails = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rent591Home.Query().
//		GroupBy(rent591home.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *Rent591HomeQuery) GroupBy(field string, fields ...string) *Rent591HomeGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Rent591HomeGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = rent591home.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Rent591Home.Query().
//		Select(rent591home.FieldTitle).
//		Scan(ctx, &v)
func (rq *Rent591HomeQuery) Select(fields ...string) *Rent591HomeSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &Rent591HomeSelect{Rent591HomeQuery: rq}
	sbuild.label = rent591home.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Rent591HomeSelect configured with the given aggregations.
func (rq *Rent591HomeQuery) Aggregate(fns ...AggregateFunc) *Rent591HomeSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *Rent591HomeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !rent591home.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *Rent591HomeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rent591Home, error) {
	var (
		nodes       = []*Rent591Home{}
		_spec       = rq.querySpec()
		loadedTypes = [3]bool{
			rq.withRent591homeTags != nil,
			rq.withRent591homeSurroundings != nil,
			rq.withRent591homeDetails != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rent591Home).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rent591Home{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withRent591homeTags; query != nil {
		if err := rq.loadRent591homeTags(ctx, query, nodes,
			func(n *Rent591Home) { n.Edges.Rent591homeTags = []*Rent591HomeTag{} },
			func(n *Rent591Home, e *Rent591HomeTag) { n.Edges.Rent591homeTags = append(n.Edges.Rent591homeTags, e) }); err != nil {
			return nil, err
		}
	}
	if query := rq.withRent591homeSurroundings; query != nil {
		if err := rq.loadRent591homeSurroundings(ctx, query, nodes, nil,
			func(n *Rent591Home, e *Rent591HomeSurrounding) { n.Edges.Rent591homeSurroundings = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withRent591homeDetails; query != nil {
		if err := rq.loadRent591homeDetails(ctx, query, nodes, nil,
			func(n *Rent591Home, e *Rent591HomeDetail) { n.Edges.Rent591homeDetails = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *Rent591HomeQuery) loadRent591homeTags(ctx context.Context, query *Rent591HomeTagQuery, nodes []*Rent591Home, init func(*Rent591Home), assign func(*Rent591Home, *Rent591HomeTag)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Rent591Home)
	nids := make(map[int]map[*Rent591Home]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(rent591home.Rent591homeTagsTable)
		s.Join(joinT).On(s.C(rent591hometag.FieldID), joinT.C(rent591home.Rent591homeTagsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(rent591home.Rent591homeTagsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(rent591home.Rent591homeTagsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Rent591Home]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Rent591HomeTag](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "rent591home_tags" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (rq *Rent591HomeQuery) loadRent591homeSurroundings(ctx context.Context, query *Rent591HomeSurroundingQuery, nodes []*Rent591Home, init func(*Rent591Home), assign func(*Rent591Home, *Rent591HomeSurrounding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Rent591Home)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Rent591HomeSurrounding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rent591home.Rent591homeSurroundingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.rent591home_rent591home_surroundings
		if fk == nil {
			return fmt.Errorf(`foreign-key "rent591home_rent591home_surroundings" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "rent591home_rent591home_surroundings" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (rq *Rent591HomeQuery) loadRent591homeDetails(ctx context.Context, query *Rent591HomeDetailQuery, nodes []*Rent591Home, init func(*Rent591Home), assign func(*Rent591Home, *Rent591HomeDetail)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Rent591Home)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Rent591HomeDetail(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(rent591home.Rent591homeDetailsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.rent591home_rent591home_details
		if fk == nil {
			return fmt.Errorf(`foreign-key "rent591home_rent591home_details" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "rent591home_rent591home_details" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *Rent591HomeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *Rent591HomeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rent591home.Table, rent591home.Columns, sqlgraph.NewFieldSpec(rent591home.FieldID, field.TypeInt))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rent591home.FieldID)
		for i := range fields {
			if fields[i] != rent591home.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *Rent591HomeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(rent591home.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = rent591home.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Rent591HomeGroupBy is the group-by builder for Rent591Home entities.
type Rent591HomeGroupBy struct {
	selector
	build *Rent591HomeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *Rent591HomeGroupBy) Aggregate(fns ...AggregateFunc) *Rent591HomeGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *Rent591HomeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeQuery, *Rent591HomeGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *Rent591HomeGroupBy) sqlScan(ctx context.Context, root *Rent591HomeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Rent591HomeSelect is the builder for selecting fields of Rent591Home entities.
type Rent591HomeSelect struct {
	*Rent591HomeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *Rent591HomeSelect) Aggregate(fns ...AggregateFunc) *Rent591HomeSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *Rent591HomeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeQuery, *Rent591HomeSelect](ctx, rs.Rent591HomeQuery, rs, rs.inters, v)
}

func (rs *Rent591HomeSelect) sqlScan(ctx context.Context, root *Rent591HomeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
