// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpositionrounddata"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpositionrounddatachildren"
)

// Rent591HomeDetailPositionRoundDataChildrenCreate is the builder for creating a Rent591HomeDetailPositionRoundDataChildren entity.
type Rent591HomeDetailPositionRoundDataChildrenCreate struct {
	config
	mutation *Rent591HomeDetailPositionRoundDataChildrenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) SetName(s string) *Rent591HomeDetailPositionRoundDataChildrenCreate {
	rdprdcc.mutation.SetName(s)
	return rdprdcc
}

// SetKey sets the "key" field.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) SetKey(s string) *Rent591HomeDetailPositionRoundDataChildrenCreate {
	rdprdcc.mutation.SetKey(s)
	return rdprdcc
}

// AddRent591homeDetailPositionRoundDataIDs adds the "rent591home_detail_position_round_datas" edge to the Rent591HomeDetailPositionRoundData entity by IDs.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) AddRent591homeDetailPositionRoundDataIDs(ids ...int) *Rent591HomeDetailPositionRoundDataChildrenCreate {
	rdprdcc.mutation.AddRent591homeDetailPositionRoundDataIDs(ids...)
	return rdprdcc
}

// AddRent591homeDetailPositionRoundDatas adds the "rent591home_detail_position_round_datas" edges to the Rent591HomeDetailPositionRoundData entity.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) AddRent591homeDetailPositionRoundDatas(r ...*Rent591HomeDetailPositionRoundData) *Rent591HomeDetailPositionRoundDataChildrenCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rdprdcc.AddRent591homeDetailPositionRoundDataIDs(ids...)
}

// Mutation returns the Rent591HomeDetailPositionRoundDataChildrenMutation object of the builder.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) Mutation() *Rent591HomeDetailPositionRoundDataChildrenMutation {
	return rdprdcc.mutation
}

// Save creates the Rent591HomeDetailPositionRoundDataChildren in the database.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) Save(ctx context.Context) (*Rent591HomeDetailPositionRoundDataChildren, error) {
	return withHooks(ctx, rdprdcc.sqlSave, rdprdcc.mutation, rdprdcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) SaveX(ctx context.Context) *Rent591HomeDetailPositionRoundDataChildren {
	v, err := rdprdcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) Exec(ctx context.Context) error {
	_, err := rdprdcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) ExecX(ctx context.Context) {
	if err := rdprdcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) check() error {
	if _, ok := rdprdcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Rent591HomeDetailPositionRoundDataChildren.name"`)}
	}
	if _, ok := rdprdcc.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Rent591HomeDetailPositionRoundDataChildren.key"`)}
	}
	return nil
}

func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) sqlSave(ctx context.Context) (*Rent591HomeDetailPositionRoundDataChildren, error) {
	if err := rdprdcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rdprdcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rdprdcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rdprdcc.mutation.id = &_node.ID
	rdprdcc.mutation.done = true
	return _node, nil
}

func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) createSpec() (*Rent591HomeDetailPositionRoundDataChildren, *sqlgraph.CreateSpec) {
	var (
		_node = &Rent591HomeDetailPositionRoundDataChildren{config: rdprdcc.config}
		_spec = sqlgraph.NewCreateSpec(rent591homedetailpositionrounddatachildren.Table, sqlgraph.NewFieldSpec(rent591homedetailpositionrounddatachildren.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rdprdcc.conflict
	if value, ok := rdprdcc.mutation.Name(); ok {
		_spec.SetField(rent591homedetailpositionrounddatachildren.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rdprdcc.mutation.Key(); ok {
		_spec.SetField(rent591homedetailpositionrounddatachildren.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if nodes := rdprdcc.mutation.Rent591homeDetailPositionRoundDatasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   rent591homedetailpositionrounddatachildren.Rent591homeDetailPositionRoundDatasTable,
			Columns: rent591homedetailpositionrounddatachildren.Rent591homeDetailPositionRoundDatasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rent591homedetailpositionrounddata.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Rent591HomeDetailPositionRoundDataChildrenUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) OnConflict(opts ...sql.ConflictOption) *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	rdprdcc.conflict = opts
	return &Rent591HomeDetailPositionRoundDataChildrenUpsertOne{
		create: rdprdcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rdprdcc *Rent591HomeDetailPositionRoundDataChildrenCreate) OnConflictColumns(columns ...string) *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	rdprdcc.conflict = append(rdprdcc.conflict, sql.ConflictColumns(columns...))
	return &Rent591HomeDetailPositionRoundDataChildrenUpsertOne{
		create: rdprdcc,
	}
}

type (
	// Rent591HomeDetailPositionRoundDataChildrenUpsertOne is the builder for "upsert"-ing
	//  one Rent591HomeDetailPositionRoundDataChildren node.
	Rent591HomeDetailPositionRoundDataChildrenUpsertOne struct {
		create *Rent591HomeDetailPositionRoundDataChildrenCreate
	}

	// Rent591HomeDetailPositionRoundDataChildrenUpsert is the "OnConflict" setter.
	Rent591HomeDetailPositionRoundDataChildrenUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsert) SetName(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsert {
	u.Set(rent591homedetailpositionrounddatachildren.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsert) UpdateName() *Rent591HomeDetailPositionRoundDataChildrenUpsert {
	u.SetExcluded(rent591homedetailpositionrounddatachildren.FieldName)
	return u
}

// SetKey sets the "key" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsert) SetKey(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsert {
	u.Set(rent591homedetailpositionrounddatachildren.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsert) UpdateKey() *Rent591HomeDetailPositionRoundDataChildrenUpsert {
	u.SetExcluded(rent591homedetailpositionrounddatachildren.FieldKey)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) UpdateNewValues() *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) Ignore() *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) DoNothing() *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Rent591HomeDetailPositionRoundDataChildrenCreate.OnConflict
// documentation for more info.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) Update(set func(*Rent591HomeDetailPositionRoundDataChildrenUpsert)) *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Rent591HomeDetailPositionRoundDataChildrenUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) SetName(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) UpdateName() *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.UpdateName()
	})
}

// SetKey sets the "key" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) SetKey(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) UpdateKey() *Rent591HomeDetailPositionRoundDataChildrenUpsertOne {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.UpdateKey()
	})
}

// Exec executes the query.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Rent591HomeDetailPositionRoundDataChildrenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Rent591HomeDetailPositionRoundDataChildrenCreateBulk is the builder for creating many Rent591HomeDetailPositionRoundDataChildren entities in bulk.
type Rent591HomeDetailPositionRoundDataChildrenCreateBulk struct {
	config
	builders []*Rent591HomeDetailPositionRoundDataChildrenCreate
	conflict []sql.ConflictOption
}

// Save creates the Rent591HomeDetailPositionRoundDataChildren entities in the database.
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) Save(ctx context.Context) ([]*Rent591HomeDetailPositionRoundDataChildren, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rdprdccb.builders))
	nodes := make([]*Rent591HomeDetailPositionRoundDataChildren, len(rdprdccb.builders))
	mutators := make([]Mutator, len(rdprdccb.builders))
	for i := range rdprdccb.builders {
		func(i int, root context.Context) {
			builder := rdprdccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Rent591HomeDetailPositionRoundDataChildrenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rdprdccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rdprdccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rdprdccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rdprdccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) SaveX(ctx context.Context) []*Rent591HomeDetailPositionRoundDataChildren {
	v, err := rdprdccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) Exec(ctx context.Context) error {
	_, err := rdprdccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) ExecX(ctx context.Context) {
	if err := rdprdccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Rent591HomeDetailPositionRoundDataChildrenUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) OnConflict(opts ...sql.ConflictOption) *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	rdprdccb.conflict = opts
	return &Rent591HomeDetailPositionRoundDataChildrenUpsertBulk{
		create: rdprdccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rdprdccb *Rent591HomeDetailPositionRoundDataChildrenCreateBulk) OnConflictColumns(columns ...string) *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	rdprdccb.conflict = append(rdprdccb.conflict, sql.ConflictColumns(columns...))
	return &Rent591HomeDetailPositionRoundDataChildrenUpsertBulk{
		create: rdprdccb,
	}
}

// Rent591HomeDetailPositionRoundDataChildrenUpsertBulk is the builder for "upsert"-ing
// a bulk of Rent591HomeDetailPositionRoundDataChildren nodes.
type Rent591HomeDetailPositionRoundDataChildrenUpsertBulk struct {
	create *Rent591HomeDetailPositionRoundDataChildrenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) UpdateNewValues() *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Rent591HomeDetailPositionRoundDataChildren.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) Ignore() *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) DoNothing() *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Rent591HomeDetailPositionRoundDataChildrenCreateBulk.OnConflict
// documentation for more info.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) Update(set func(*Rent591HomeDetailPositionRoundDataChildrenUpsert)) *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Rent591HomeDetailPositionRoundDataChildrenUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) SetName(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) UpdateName() *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.UpdateName()
	})
}

// SetKey sets the "key" field.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) SetKey(v string) *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) UpdateKey() *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk {
	return u.Update(func(s *Rent591HomeDetailPositionRoundDataChildrenUpsert) {
		s.UpdateKey()
	})
}

// Exec executes the query.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Rent591HomeDetailPositionRoundDataChildrenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Rent591HomeDetailPositionRoundDataChildrenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Rent591HomeDetailPositionRoundDataChildrenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
