// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetail"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpositionround"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpositionrounddata"
)

// Rent591HomeDetailPositionRoundQuery is the builder for querying Rent591HomeDetailPositionRound entities.
type Rent591HomeDetailPositionRoundQuery struct {
	config
	ctx                                     *QueryContext
	order                                   []rent591homedetailpositionround.OrderOption
	inters                                  []Interceptor
	predicates                              []predicate.Rent591HomeDetailPositionRound
	withRent591homeDetails                  *Rent591HomeDetailQuery
	withRent591homeDetailPositionRoundDatas *Rent591HomeDetailPositionRoundDataQuery
	withFKs                                 bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Rent591HomeDetailPositionRoundQuery builder.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Where(ps ...predicate.Rent591HomeDetailPositionRound) *Rent591HomeDetailPositionRoundQuery {
	rdprq.predicates = append(rdprq.predicates, ps...)
	return rdprq
}

// Limit the number of records to be returned by this query.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Limit(limit int) *Rent591HomeDetailPositionRoundQuery {
	rdprq.ctx.Limit = &limit
	return rdprq
}

// Offset to start from.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Offset(offset int) *Rent591HomeDetailPositionRoundQuery {
	rdprq.ctx.Offset = &offset
	return rdprq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Unique(unique bool) *Rent591HomeDetailPositionRoundQuery {
	rdprq.ctx.Unique = &unique
	return rdprq
}

// Order specifies how the records should be ordered.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Order(o ...rent591homedetailpositionround.OrderOption) *Rent591HomeDetailPositionRoundQuery {
	rdprq.order = append(rdprq.order, o...)
	return rdprq
}

// QueryRent591homeDetails chains the current query on the "rent591home_details" edge.
func (rdprq *Rent591HomeDetailPositionRoundQuery) QueryRent591homeDetails() *Rent591HomeDetailQuery {
	query := (&Rent591HomeDetailClient{config: rdprq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rdprq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rdprq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591homedetailpositionround.Table, rent591homedetailpositionround.FieldID, selector),
			sqlgraph.To(rent591homedetail.Table, rent591homedetail.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, rent591homedetailpositionround.Rent591homeDetailsTable, rent591homedetailpositionround.Rent591homeDetailsColumn),
		)
		fromU = sqlgraph.SetNeighbors(rdprq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRent591homeDetailPositionRoundDatas chains the current query on the "rent591home_detail_position_round_datas" edge.
func (rdprq *Rent591HomeDetailPositionRoundQuery) QueryRent591homeDetailPositionRoundDatas() *Rent591HomeDetailPositionRoundDataQuery {
	query := (&Rent591HomeDetailPositionRoundDataClient{config: rdprq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rdprq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rdprq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591homedetailpositionround.Table, rent591homedetailpositionround.FieldID, selector),
			sqlgraph.To(rent591homedetailpositionrounddata.Table, rent591homedetailpositionrounddata.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasTable, rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rdprq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rent591HomeDetailPositionRound entity from the query.
// Returns a *NotFoundError when no Rent591HomeDetailPositionRound was found.
func (rdprq *Rent591HomeDetailPositionRoundQuery) First(ctx context.Context) (*Rent591HomeDetailPositionRound, error) {
	nodes, err := rdprq.Limit(1).All(setContextOp(ctx, rdprq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rent591homedetailpositionround.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) FirstX(ctx context.Context) *Rent591HomeDetailPositionRound {
	node, err := rdprq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rent591HomeDetailPositionRound ID from the query.
// Returns a *NotFoundError when no Rent591HomeDetailPositionRound ID was found.
func (rdprq *Rent591HomeDetailPositionRoundQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdprq.Limit(1).IDs(setContextOp(ctx, rdprq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rent591homedetailpositionround.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) FirstIDX(ctx context.Context) int {
	id, err := rdprq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rent591HomeDetailPositionRound entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rent591HomeDetailPositionRound entity is found.
// Returns a *NotFoundError when no Rent591HomeDetailPositionRound entities are found.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Only(ctx context.Context) (*Rent591HomeDetailPositionRound, error) {
	nodes, err := rdprq.Limit(2).All(setContextOp(ctx, rdprq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rent591homedetailpositionround.Label}
	default:
		return nil, &NotSingularError{rent591homedetailpositionround.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) OnlyX(ctx context.Context) *Rent591HomeDetailPositionRound {
	node, err := rdprq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rent591HomeDetailPositionRound ID in the query.
// Returns a *NotSingularError when more than one Rent591HomeDetailPositionRound ID is found.
// Returns a *NotFoundError when no entities are found.
func (rdprq *Rent591HomeDetailPositionRoundQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdprq.Limit(2).IDs(setContextOp(ctx, rdprq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rent591homedetailpositionround.Label}
	default:
		err = &NotSingularError{rent591homedetailpositionround.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) OnlyIDX(ctx context.Context) int {
	id, err := rdprq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rent591HomeDetailPositionRounds.
func (rdprq *Rent591HomeDetailPositionRoundQuery) All(ctx context.Context) ([]*Rent591HomeDetailPositionRound, error) {
	ctx = setContextOp(ctx, rdprq.ctx, "All")
	if err := rdprq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rent591HomeDetailPositionRound, *Rent591HomeDetailPositionRoundQuery]()
	return withInterceptors[[]*Rent591HomeDetailPositionRound](ctx, rdprq, qr, rdprq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) AllX(ctx context.Context) []*Rent591HomeDetailPositionRound {
	nodes, err := rdprq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rent591HomeDetailPositionRound IDs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rdprq.ctx.Unique == nil && rdprq.path != nil {
		rdprq.Unique(true)
	}
	ctx = setContextOp(ctx, rdprq.ctx, "IDs")
	if err = rdprq.Select(rent591homedetailpositionround.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) IDsX(ctx context.Context) []int {
	ids, err := rdprq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rdprq.ctx, "Count")
	if err := rdprq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rdprq, querierCount[*Rent591HomeDetailPositionRoundQuery](), rdprq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) CountX(ctx context.Context) int {
	count, err := rdprq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rdprq.ctx, "Exist")
	switch _, err := rdprq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rdprq *Rent591HomeDetailPositionRoundQuery) ExistX(ctx context.Context) bool {
	exist, err := rdprq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Rent591HomeDetailPositionRoundQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Clone() *Rent591HomeDetailPositionRoundQuery {
	if rdprq == nil {
		return nil
	}
	return &Rent591HomeDetailPositionRoundQuery{
		config:                                  rdprq.config,
		ctx:                                     rdprq.ctx.Clone(),
		order:                                   append([]rent591homedetailpositionround.OrderOption{}, rdprq.order...),
		inters:                                  append([]Interceptor{}, rdprq.inters...),
		predicates:                              append([]predicate.Rent591HomeDetailPositionRound{}, rdprq.predicates...),
		withRent591homeDetails:                  rdprq.withRent591homeDetails.Clone(),
		withRent591homeDetailPositionRoundDatas: rdprq.withRent591homeDetailPositionRoundDatas.Clone(),
		// clone intermediate query.
		sql:  rdprq.sql.Clone(),
		path: rdprq.path,
	}
}

// WithRent591homeDetails tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_details" edge. The optional arguments are used to configure the query builder of the edge.
func (rdprq *Rent591HomeDetailPositionRoundQuery) WithRent591homeDetails(opts ...func(*Rent591HomeDetailQuery)) *Rent591HomeDetailPositionRoundQuery {
	query := (&Rent591HomeDetailClient{config: rdprq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rdprq.withRent591homeDetails = query
	return rdprq
}

// WithRent591homeDetailPositionRoundDatas tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_detail_position_round_datas" edge. The optional arguments are used to configure the query builder of the edge.
func (rdprq *Rent591HomeDetailPositionRoundQuery) WithRent591homeDetailPositionRoundDatas(opts ...func(*Rent591HomeDetailPositionRoundDataQuery)) *Rent591HomeDetailPositionRoundQuery {
	query := (&Rent591HomeDetailPositionRoundDataClient{config: rdprq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rdprq.withRent591homeDetailPositionRoundDatas = query
	return rdprq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rent591HomeDetailPositionRound.Query().
//		GroupBy(rent591homedetailpositionround.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rdprq *Rent591HomeDetailPositionRoundQuery) GroupBy(field string, fields ...string) *Rent591HomeDetailPositionRoundGroupBy {
	rdprq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Rent591HomeDetailPositionRoundGroupBy{build: rdprq}
	grbuild.flds = &rdprq.ctx.Fields
	grbuild.label = rent591homedetailpositionround.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Rent591HomeDetailPositionRound.Query().
//		Select(rent591homedetailpositionround.FieldTitle).
//		Scan(ctx, &v)
func (rdprq *Rent591HomeDetailPositionRoundQuery) Select(fields ...string) *Rent591HomeDetailPositionRoundSelect {
	rdprq.ctx.Fields = append(rdprq.ctx.Fields, fields...)
	sbuild := &Rent591HomeDetailPositionRoundSelect{Rent591HomeDetailPositionRoundQuery: rdprq}
	sbuild.label = rent591homedetailpositionround.Label
	sbuild.flds, sbuild.scan = &rdprq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Rent591HomeDetailPositionRoundSelect configured with the given aggregations.
func (rdprq *Rent591HomeDetailPositionRoundQuery) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPositionRoundSelect {
	return rdprq.Select().Aggregate(fns...)
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rdprq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rdprq); err != nil {
				return err
			}
		}
	}
	for _, f := range rdprq.ctx.Fields {
		if !rent591homedetailpositionround.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rdprq.path != nil {
		prev, err := rdprq.path(ctx)
		if err != nil {
			return err
		}
		rdprq.sql = prev
	}
	return nil
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rent591HomeDetailPositionRound, error) {
	var (
		nodes       = []*Rent591HomeDetailPositionRound{}
		withFKs     = rdprq.withFKs
		_spec       = rdprq.querySpec()
		loadedTypes = [2]bool{
			rdprq.withRent591homeDetails != nil,
			rdprq.withRent591homeDetailPositionRoundDatas != nil,
		}
	)
	if rdprq.withRent591homeDetails != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, rent591homedetailpositionround.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rent591HomeDetailPositionRound).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rent591HomeDetailPositionRound{config: rdprq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rdprq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rdprq.withRent591homeDetails; query != nil {
		if err := rdprq.loadRent591homeDetails(ctx, query, nodes, nil,
			func(n *Rent591HomeDetailPositionRound, e *Rent591HomeDetail) { n.Edges.Rent591homeDetails = e }); err != nil {
			return nil, err
		}
	}
	if query := rdprq.withRent591homeDetailPositionRoundDatas; query != nil {
		if err := rdprq.loadRent591homeDetailPositionRoundDatas(ctx, query, nodes,
			func(n *Rent591HomeDetailPositionRound) {
				n.Edges.Rent591homeDetailPositionRoundDatas = []*Rent591HomeDetailPositionRoundData{}
			},
			func(n *Rent591HomeDetailPositionRound, e *Rent591HomeDetailPositionRoundData) {
				n.Edges.Rent591homeDetailPositionRoundDatas = append(n.Edges.Rent591homeDetailPositionRoundDatas, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) loadRent591homeDetails(ctx context.Context, query *Rent591HomeDetailQuery, nodes []*Rent591HomeDetailPositionRound, init func(*Rent591HomeDetailPositionRound), assign func(*Rent591HomeDetailPositionRound, *Rent591HomeDetail)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Rent591HomeDetailPositionRound)
	for i := range nodes {
		if nodes[i].rent591home_detail_rent591home_detail_position_rounds == nil {
			continue
		}
		fk := *nodes[i].rent591home_detail_rent591home_detail_position_rounds
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(rent591homedetail.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "rent591home_detail_rent591home_detail_position_rounds" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rdprq *Rent591HomeDetailPositionRoundQuery) loadRent591homeDetailPositionRoundDatas(ctx context.Context, query *Rent591HomeDetailPositionRoundDataQuery, nodes []*Rent591HomeDetailPositionRound, init func(*Rent591HomeDetailPositionRound), assign func(*Rent591HomeDetailPositionRound, *Rent591HomeDetailPositionRoundData)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Rent591HomeDetailPositionRound)
	nids := make(map[int]map[*Rent591HomeDetailPositionRound]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasTable)
		s.Join(joinT).On(s.C(rent591homedetailpositionrounddata.FieldID), joinT.C(rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(rent591homedetailpositionround.Rent591homeDetailPositionRoundDatasPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Rent591HomeDetailPositionRound]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Rent591HomeDetailPositionRoundData](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "rent591home_detail_position_round_datas" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rdprq.querySpec()
	_spec.Node.Columns = rdprq.ctx.Fields
	if len(rdprq.ctx.Fields) > 0 {
		_spec.Unique = rdprq.ctx.Unique != nil && *rdprq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rdprq.driver, _spec)
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rent591homedetailpositionround.Table, rent591homedetailpositionround.Columns, sqlgraph.NewFieldSpec(rent591homedetailpositionround.FieldID, field.TypeInt))
	_spec.From = rdprq.sql
	if unique := rdprq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rdprq.path != nil {
		_spec.Unique = true
	}
	if fields := rdprq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rent591homedetailpositionround.FieldID)
		for i := range fields {
			if fields[i] != rent591homedetailpositionround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rdprq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rdprq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rdprq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rdprq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rdprq *Rent591HomeDetailPositionRoundQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rdprq.driver.Dialect())
	t1 := builder.Table(rent591homedetailpositionround.Table)
	columns := rdprq.ctx.Fields
	if len(columns) == 0 {
		columns = rent591homedetailpositionround.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rdprq.sql != nil {
		selector = rdprq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rdprq.ctx.Unique != nil && *rdprq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rdprq.predicates {
		p(selector)
	}
	for _, p := range rdprq.order {
		p(selector)
	}
	if offset := rdprq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rdprq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Rent591HomeDetailPositionRoundGroupBy is the group-by builder for Rent591HomeDetailPositionRound entities.
type Rent591HomeDetailPositionRoundGroupBy struct {
	selector
	build *Rent591HomeDetailPositionRoundQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rdprgb *Rent591HomeDetailPositionRoundGroupBy) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPositionRoundGroupBy {
	rdprgb.fns = append(rdprgb.fns, fns...)
	return rdprgb
}

// Scan applies the selector query and scans the result into the given value.
func (rdprgb *Rent591HomeDetailPositionRoundGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdprgb.build.ctx, "GroupBy")
	if err := rdprgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailPositionRoundQuery, *Rent591HomeDetailPositionRoundGroupBy](ctx, rdprgb.build, rdprgb, rdprgb.build.inters, v)
}

func (rdprgb *Rent591HomeDetailPositionRoundGroupBy) sqlScan(ctx context.Context, root *Rent591HomeDetailPositionRoundQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rdprgb.fns))
	for _, fn := range rdprgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rdprgb.flds)+len(rdprgb.fns))
		for _, f := range *rdprgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rdprgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdprgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Rent591HomeDetailPositionRoundSelect is the builder for selecting fields of Rent591HomeDetailPositionRound entities.
type Rent591HomeDetailPositionRoundSelect struct {
	*Rent591HomeDetailPositionRoundQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rdprs *Rent591HomeDetailPositionRoundSelect) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPositionRoundSelect {
	rdprs.fns = append(rdprs.fns, fns...)
	return rdprs
}

// Scan applies the selector query and scans the result into the given value.
func (rdprs *Rent591HomeDetailPositionRoundSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdprs.ctx, "Select")
	if err := rdprs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailPositionRoundQuery, *Rent591HomeDetailPositionRoundSelect](ctx, rdprs.Rent591HomeDetailPositionRoundQuery, rdprs, rdprs.inters, v)
}

func (rdprs *Rent591HomeDetailPositionRoundSelect) sqlScan(ctx context.Context, root *Rent591HomeDetailPositionRoundQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rdprs.fns))
	for _, fn := range rdprs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rdprs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdprs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
