// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetail"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpublish"
)

// Rent591HomeDetailPublishQuery is the builder for querying Rent591HomeDetailPublish entities.
type Rent591HomeDetailPublishQuery struct {
	config
	ctx                    *QueryContext
	order                  []rent591homedetailpublish.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Rent591HomeDetailPublish
	withRent591homeDetails *Rent591HomeDetailQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Rent591HomeDetailPublishQuery builder.
func (rdpq *Rent591HomeDetailPublishQuery) Where(ps ...predicate.Rent591HomeDetailPublish) *Rent591HomeDetailPublishQuery {
	rdpq.predicates = append(rdpq.predicates, ps...)
	return rdpq
}

// Limit the number of records to be returned by this query.
func (rdpq *Rent591HomeDetailPublishQuery) Limit(limit int) *Rent591HomeDetailPublishQuery {
	rdpq.ctx.Limit = &limit
	return rdpq
}

// Offset to start from.
func (rdpq *Rent591HomeDetailPublishQuery) Offset(offset int) *Rent591HomeDetailPublishQuery {
	rdpq.ctx.Offset = &offset
	return rdpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rdpq *Rent591HomeDetailPublishQuery) Unique(unique bool) *Rent591HomeDetailPublishQuery {
	rdpq.ctx.Unique = &unique
	return rdpq
}

// Order specifies how the records should be ordered.
func (rdpq *Rent591HomeDetailPublishQuery) Order(o ...rent591homedetailpublish.OrderOption) *Rent591HomeDetailPublishQuery {
	rdpq.order = append(rdpq.order, o...)
	return rdpq
}

// QueryRent591homeDetails chains the current query on the "rent591home_details" edge.
func (rdpq *Rent591HomeDetailPublishQuery) QueryRent591homeDetails() *Rent591HomeDetailQuery {
	query := (&Rent591HomeDetailClient{config: rdpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rdpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rdpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591homedetailpublish.Table, rent591homedetailpublish.FieldID, selector),
			sqlgraph.To(rent591homedetail.Table, rent591homedetail.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, rent591homedetailpublish.Rent591homeDetailsTable, rent591homedetailpublish.Rent591homeDetailsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rdpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rent591HomeDetailPublish entity from the query.
// Returns a *NotFoundError when no Rent591HomeDetailPublish was found.
func (rdpq *Rent591HomeDetailPublishQuery) First(ctx context.Context) (*Rent591HomeDetailPublish, error) {
	nodes, err := rdpq.Limit(1).All(setContextOp(ctx, rdpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rent591homedetailpublish.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) FirstX(ctx context.Context) *Rent591HomeDetailPublish {
	node, err := rdpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rent591HomeDetailPublish ID from the query.
// Returns a *NotFoundError when no Rent591HomeDetailPublish ID was found.
func (rdpq *Rent591HomeDetailPublishQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdpq.Limit(1).IDs(setContextOp(ctx, rdpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rent591homedetailpublish.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) FirstIDX(ctx context.Context) int {
	id, err := rdpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rent591HomeDetailPublish entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rent591HomeDetailPublish entity is found.
// Returns a *NotFoundError when no Rent591HomeDetailPublish entities are found.
func (rdpq *Rent591HomeDetailPublishQuery) Only(ctx context.Context) (*Rent591HomeDetailPublish, error) {
	nodes, err := rdpq.Limit(2).All(setContextOp(ctx, rdpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rent591homedetailpublish.Label}
	default:
		return nil, &NotSingularError{rent591homedetailpublish.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) OnlyX(ctx context.Context) *Rent591HomeDetailPublish {
	node, err := rdpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rent591HomeDetailPublish ID in the query.
// Returns a *NotSingularError when more than one Rent591HomeDetailPublish ID is found.
// Returns a *NotFoundError when no entities are found.
func (rdpq *Rent591HomeDetailPublishQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdpq.Limit(2).IDs(setContextOp(ctx, rdpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rent591homedetailpublish.Label}
	default:
		err = &NotSingularError{rent591homedetailpublish.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) OnlyIDX(ctx context.Context) int {
	id, err := rdpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rent591HomeDetailPublishes.
func (rdpq *Rent591HomeDetailPublishQuery) All(ctx context.Context) ([]*Rent591HomeDetailPublish, error) {
	ctx = setContextOp(ctx, rdpq.ctx, "All")
	if err := rdpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rent591HomeDetailPublish, *Rent591HomeDetailPublishQuery]()
	return withInterceptors[[]*Rent591HomeDetailPublish](ctx, rdpq, qr, rdpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) AllX(ctx context.Context) []*Rent591HomeDetailPublish {
	nodes, err := rdpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rent591HomeDetailPublish IDs.
func (rdpq *Rent591HomeDetailPublishQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rdpq.ctx.Unique == nil && rdpq.path != nil {
		rdpq.Unique(true)
	}
	ctx = setContextOp(ctx, rdpq.ctx, "IDs")
	if err = rdpq.Select(rent591homedetailpublish.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) IDsX(ctx context.Context) []int {
	ids, err := rdpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rdpq *Rent591HomeDetailPublishQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rdpq.ctx, "Count")
	if err := rdpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rdpq, querierCount[*Rent591HomeDetailPublishQuery](), rdpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) CountX(ctx context.Context) int {
	count, err := rdpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rdpq *Rent591HomeDetailPublishQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rdpq.ctx, "Exist")
	switch _, err := rdpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rdpq *Rent591HomeDetailPublishQuery) ExistX(ctx context.Context) bool {
	exist, err := rdpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Rent591HomeDetailPublishQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rdpq *Rent591HomeDetailPublishQuery) Clone() *Rent591HomeDetailPublishQuery {
	if rdpq == nil {
		return nil
	}
	return &Rent591HomeDetailPublishQuery{
		config:                 rdpq.config,
		ctx:                    rdpq.ctx.Clone(),
		order:                  append([]rent591homedetailpublish.OrderOption{}, rdpq.order...),
		inters:                 append([]Interceptor{}, rdpq.inters...),
		predicates:             append([]predicate.Rent591HomeDetailPublish{}, rdpq.predicates...),
		withRent591homeDetails: rdpq.withRent591homeDetails.Clone(),
		// clone intermediate query.
		sql:  rdpq.sql.Clone(),
		path: rdpq.path,
	}
}

// WithRent591homeDetails tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_details" edge. The optional arguments are used to configure the query builder of the edge.
func (rdpq *Rent591HomeDetailPublishQuery) WithRent591homeDetails(opts ...func(*Rent591HomeDetailQuery)) *Rent591HomeDetailPublishQuery {
	query := (&Rent591HomeDetailClient{config: rdpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rdpq.withRent591homeDetails = query
	return rdpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rent591HomeDetailPublish.Query().
//		GroupBy(rent591homedetailpublish.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rdpq *Rent591HomeDetailPublishQuery) GroupBy(field string, fields ...string) *Rent591HomeDetailPublishGroupBy {
	rdpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Rent591HomeDetailPublishGroupBy{build: rdpq}
	grbuild.flds = &rdpq.ctx.Fields
	grbuild.label = rent591homedetailpublish.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID int `json:"post_id,omitempty"`
//	}
//
//	client.Rent591HomeDetailPublish.Query().
//		Select(rent591homedetailpublish.FieldPostID).
//		Scan(ctx, &v)
func (rdpq *Rent591HomeDetailPublishQuery) Select(fields ...string) *Rent591HomeDetailPublishSelect {
	rdpq.ctx.Fields = append(rdpq.ctx.Fields, fields...)
	sbuild := &Rent591HomeDetailPublishSelect{Rent591HomeDetailPublishQuery: rdpq}
	sbuild.label = rent591homedetailpublish.Label
	sbuild.flds, sbuild.scan = &rdpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Rent591HomeDetailPublishSelect configured with the given aggregations.
func (rdpq *Rent591HomeDetailPublishQuery) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPublishSelect {
	return rdpq.Select().Aggregate(fns...)
}

func (rdpq *Rent591HomeDetailPublishQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rdpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rdpq); err != nil {
				return err
			}
		}
	}
	for _, f := range rdpq.ctx.Fields {
		if !rent591homedetailpublish.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rdpq.path != nil {
		prev, err := rdpq.path(ctx)
		if err != nil {
			return err
		}
		rdpq.sql = prev
	}
	return nil
}

func (rdpq *Rent591HomeDetailPublishQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rent591HomeDetailPublish, error) {
	var (
		nodes       = []*Rent591HomeDetailPublish{}
		_spec       = rdpq.querySpec()
		loadedTypes = [1]bool{
			rdpq.withRent591homeDetails != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rent591HomeDetailPublish).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rent591HomeDetailPublish{config: rdpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rdpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rdpq.withRent591homeDetails; query != nil {
		if err := rdpq.loadRent591homeDetails(ctx, query, nodes,
			func(n *Rent591HomeDetailPublish) { n.Edges.Rent591homeDetails = []*Rent591HomeDetail{} },
			func(n *Rent591HomeDetailPublish, e *Rent591HomeDetail) {
				n.Edges.Rent591homeDetails = append(n.Edges.Rent591homeDetails, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rdpq *Rent591HomeDetailPublishQuery) loadRent591homeDetails(ctx context.Context, query *Rent591HomeDetailQuery, nodes []*Rent591HomeDetailPublish, init func(*Rent591HomeDetailPublish), assign func(*Rent591HomeDetailPublish, *Rent591HomeDetail)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Rent591HomeDetailPublish)
	nids := make(map[int]map[*Rent591HomeDetailPublish]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(rent591homedetailpublish.Rent591homeDetailsTable)
		s.Join(joinT).On(s.C(rent591homedetail.FieldID), joinT.C(rent591homedetailpublish.Rent591homeDetailsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(rent591homedetailpublish.Rent591homeDetailsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(rent591homedetailpublish.Rent591homeDetailsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Rent591HomeDetailPublish]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Rent591HomeDetail](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "rent591home_details" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rdpq *Rent591HomeDetailPublishQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rdpq.querySpec()
	_spec.Node.Columns = rdpq.ctx.Fields
	if len(rdpq.ctx.Fields) > 0 {
		_spec.Unique = rdpq.ctx.Unique != nil && *rdpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rdpq.driver, _spec)
}

func (rdpq *Rent591HomeDetailPublishQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rent591homedetailpublish.Table, rent591homedetailpublish.Columns, sqlgraph.NewFieldSpec(rent591homedetailpublish.FieldID, field.TypeInt))
	_spec.From = rdpq.sql
	if unique := rdpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rdpq.path != nil {
		_spec.Unique = true
	}
	if fields := rdpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rent591homedetailpublish.FieldID)
		for i := range fields {
			if fields[i] != rent591homedetailpublish.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rdpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rdpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rdpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rdpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rdpq *Rent591HomeDetailPublishQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rdpq.driver.Dialect())
	t1 := builder.Table(rent591homedetailpublish.Table)
	columns := rdpq.ctx.Fields
	if len(columns) == 0 {
		columns = rent591homedetailpublish.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rdpq.sql != nil {
		selector = rdpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rdpq.ctx.Unique != nil && *rdpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rdpq.predicates {
		p(selector)
	}
	for _, p := range rdpq.order {
		p(selector)
	}
	if offset := rdpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rdpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Rent591HomeDetailPublishGroupBy is the group-by builder for Rent591HomeDetailPublish entities.
type Rent591HomeDetailPublishGroupBy struct {
	selector
	build *Rent591HomeDetailPublishQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rdpgb *Rent591HomeDetailPublishGroupBy) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPublishGroupBy {
	rdpgb.fns = append(rdpgb.fns, fns...)
	return rdpgb
}

// Scan applies the selector query and scans the result into the given value.
func (rdpgb *Rent591HomeDetailPublishGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdpgb.build.ctx, "GroupBy")
	if err := rdpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailPublishQuery, *Rent591HomeDetailPublishGroupBy](ctx, rdpgb.build, rdpgb, rdpgb.build.inters, v)
}

func (rdpgb *Rent591HomeDetailPublishGroupBy) sqlScan(ctx context.Context, root *Rent591HomeDetailPublishQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rdpgb.fns))
	for _, fn := range rdpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rdpgb.flds)+len(rdpgb.fns))
		for _, f := range *rdpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rdpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Rent591HomeDetailPublishSelect is the builder for selecting fields of Rent591HomeDetailPublish entities.
type Rent591HomeDetailPublishSelect struct {
	*Rent591HomeDetailPublishQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rdps *Rent591HomeDetailPublishSelect) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailPublishSelect {
	rdps.fns = append(rdps.fns, fns...)
	return rdps
}

// Scan applies the selector query and scans the result into the given value.
func (rdps *Rent591HomeDetailPublishSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdps.ctx, "Select")
	if err := rdps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailPublishQuery, *Rent591HomeDetailPublishSelect](ctx, rdps.Rent591HomeDetailPublishQuery, rdps, rdps.inters, v)
}

func (rdps *Rent591HomeDetailPublishSelect) sqlScan(ctx context.Context, root *Rent591HomeDetailPublishQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rdps.fns))
	for _, fn := range rdps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rdps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
