// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetail"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailinfo"
)

// Rent591HomeDetailInfoQuery is the builder for querying Rent591HomeDetailInfo entities.
type Rent591HomeDetailInfoQuery struct {
	config
	ctx                    *QueryContext
	order                  []rent591homedetailinfo.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Rent591HomeDetailInfo
	withRent591homeDetails *Rent591HomeDetailQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Rent591HomeDetailInfoQuery builder.
func (rdiq *Rent591HomeDetailInfoQuery) Where(ps ...predicate.Rent591HomeDetailInfo) *Rent591HomeDetailInfoQuery {
	rdiq.predicates = append(rdiq.predicates, ps...)
	return rdiq
}

// Limit the number of records to be returned by this query.
func (rdiq *Rent591HomeDetailInfoQuery) Limit(limit int) *Rent591HomeDetailInfoQuery {
	rdiq.ctx.Limit = &limit
	return rdiq
}

// Offset to start from.
func (rdiq *Rent591HomeDetailInfoQuery) Offset(offset int) *Rent591HomeDetailInfoQuery {
	rdiq.ctx.Offset = &offset
	return rdiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rdiq *Rent591HomeDetailInfoQuery) Unique(unique bool) *Rent591HomeDetailInfoQuery {
	rdiq.ctx.Unique = &unique
	return rdiq
}

// Order specifies how the records should be ordered.
func (rdiq *Rent591HomeDetailInfoQuery) Order(o ...rent591homedetailinfo.OrderOption) *Rent591HomeDetailInfoQuery {
	rdiq.order = append(rdiq.order, o...)
	return rdiq
}

// QueryRent591homeDetails chains the current query on the "rent591home_details" edge.
func (rdiq *Rent591HomeDetailInfoQuery) QueryRent591homeDetails() *Rent591HomeDetailQuery {
	query := (&Rent591HomeDetailClient{config: rdiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rdiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rdiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591homedetailinfo.Table, rent591homedetailinfo.FieldID, selector),
			sqlgraph.To(rent591homedetail.Table, rent591homedetail.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, rent591homedetailinfo.Rent591homeDetailsTable, rent591homedetailinfo.Rent591homeDetailsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rdiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rent591HomeDetailInfo entity from the query.
// Returns a *NotFoundError when no Rent591HomeDetailInfo was found.
func (rdiq *Rent591HomeDetailInfoQuery) First(ctx context.Context) (*Rent591HomeDetailInfo, error) {
	nodes, err := rdiq.Limit(1).All(setContextOp(ctx, rdiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rent591homedetailinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) FirstX(ctx context.Context) *Rent591HomeDetailInfo {
	node, err := rdiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rent591HomeDetailInfo ID from the query.
// Returns a *NotFoundError when no Rent591HomeDetailInfo ID was found.
func (rdiq *Rent591HomeDetailInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdiq.Limit(1).IDs(setContextOp(ctx, rdiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rent591homedetailinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := rdiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rent591HomeDetailInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rent591HomeDetailInfo entity is found.
// Returns a *NotFoundError when no Rent591HomeDetailInfo entities are found.
func (rdiq *Rent591HomeDetailInfoQuery) Only(ctx context.Context) (*Rent591HomeDetailInfo, error) {
	nodes, err := rdiq.Limit(2).All(setContextOp(ctx, rdiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rent591homedetailinfo.Label}
	default:
		return nil, &NotSingularError{rent591homedetailinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) OnlyX(ctx context.Context) *Rent591HomeDetailInfo {
	node, err := rdiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rent591HomeDetailInfo ID in the query.
// Returns a *NotSingularError when more than one Rent591HomeDetailInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (rdiq *Rent591HomeDetailInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rdiq.Limit(2).IDs(setContextOp(ctx, rdiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rent591homedetailinfo.Label}
	default:
		err = &NotSingularError{rent591homedetailinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := rdiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rent591HomeDetailInfos.
func (rdiq *Rent591HomeDetailInfoQuery) All(ctx context.Context) ([]*Rent591HomeDetailInfo, error) {
	ctx = setContextOp(ctx, rdiq.ctx, "All")
	if err := rdiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rent591HomeDetailInfo, *Rent591HomeDetailInfoQuery]()
	return withInterceptors[[]*Rent591HomeDetailInfo](ctx, rdiq, qr, rdiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) AllX(ctx context.Context) []*Rent591HomeDetailInfo {
	nodes, err := rdiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rent591HomeDetailInfo IDs.
func (rdiq *Rent591HomeDetailInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rdiq.ctx.Unique == nil && rdiq.path != nil {
		rdiq.Unique(true)
	}
	ctx = setContextOp(ctx, rdiq.ctx, "IDs")
	if err = rdiq.Select(rent591homedetailinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := rdiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rdiq *Rent591HomeDetailInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rdiq.ctx, "Count")
	if err := rdiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rdiq, querierCount[*Rent591HomeDetailInfoQuery](), rdiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) CountX(ctx context.Context) int {
	count, err := rdiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rdiq *Rent591HomeDetailInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rdiq.ctx, "Exist")
	switch _, err := rdiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rdiq *Rent591HomeDetailInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := rdiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Rent591HomeDetailInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rdiq *Rent591HomeDetailInfoQuery) Clone() *Rent591HomeDetailInfoQuery {
	if rdiq == nil {
		return nil
	}
	return &Rent591HomeDetailInfoQuery{
		config:                 rdiq.config,
		ctx:                    rdiq.ctx.Clone(),
		order:                  append([]rent591homedetailinfo.OrderOption{}, rdiq.order...),
		inters:                 append([]Interceptor{}, rdiq.inters...),
		predicates:             append([]predicate.Rent591HomeDetailInfo{}, rdiq.predicates...),
		withRent591homeDetails: rdiq.withRent591homeDetails.Clone(),
		// clone intermediate query.
		sql:  rdiq.sql.Clone(),
		path: rdiq.path,
	}
}

// WithRent591homeDetails tells the query-builder to eager-load the nodes that are connected to
// the "rent591home_details" edge. The optional arguments are used to configure the query builder of the edge.
func (rdiq *Rent591HomeDetailInfoQuery) WithRent591homeDetails(opts ...func(*Rent591HomeDetailQuery)) *Rent591HomeDetailInfoQuery {
	query := (&Rent591HomeDetailClient{config: rdiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rdiq.withRent591homeDetails = query
	return rdiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rent591HomeDetailInfo.Query().
//		GroupBy(rent591homedetailinfo.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rdiq *Rent591HomeDetailInfoQuery) GroupBy(field string, fields ...string) *Rent591HomeDetailInfoGroupBy {
	rdiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Rent591HomeDetailInfoGroupBy{build: rdiq}
	grbuild.flds = &rdiq.ctx.Fields
	grbuild.label = rent591homedetailinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Rent591HomeDetailInfo.Query().
//		Select(rent591homedetailinfo.FieldName).
//		Scan(ctx, &v)
func (rdiq *Rent591HomeDetailInfoQuery) Select(fields ...string) *Rent591HomeDetailInfoSelect {
	rdiq.ctx.Fields = append(rdiq.ctx.Fields, fields...)
	sbuild := &Rent591HomeDetailInfoSelect{Rent591HomeDetailInfoQuery: rdiq}
	sbuild.label = rent591homedetailinfo.Label
	sbuild.flds, sbuild.scan = &rdiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Rent591HomeDetailInfoSelect configured with the given aggregations.
func (rdiq *Rent591HomeDetailInfoQuery) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailInfoSelect {
	return rdiq.Select().Aggregate(fns...)
}

func (rdiq *Rent591HomeDetailInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rdiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rdiq); err != nil {
				return err
			}
		}
	}
	for _, f := range rdiq.ctx.Fields {
		if !rent591homedetailinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rdiq.path != nil {
		prev, err := rdiq.path(ctx)
		if err != nil {
			return err
		}
		rdiq.sql = prev
	}
	return nil
}

func (rdiq *Rent591HomeDetailInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rent591HomeDetailInfo, error) {
	var (
		nodes       = []*Rent591HomeDetailInfo{}
		_spec       = rdiq.querySpec()
		loadedTypes = [1]bool{
			rdiq.withRent591homeDetails != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rent591HomeDetailInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rent591HomeDetailInfo{config: rdiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rdiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rdiq.withRent591homeDetails; query != nil {
		if err := rdiq.loadRent591homeDetails(ctx, query, nodes,
			func(n *Rent591HomeDetailInfo) { n.Edges.Rent591homeDetails = []*Rent591HomeDetail{} },
			func(n *Rent591HomeDetailInfo, e *Rent591HomeDetail) {
				n.Edges.Rent591homeDetails = append(n.Edges.Rent591homeDetails, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rdiq *Rent591HomeDetailInfoQuery) loadRent591homeDetails(ctx context.Context, query *Rent591HomeDetailQuery, nodes []*Rent591HomeDetailInfo, init func(*Rent591HomeDetailInfo), assign func(*Rent591HomeDetailInfo, *Rent591HomeDetail)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Rent591HomeDetailInfo)
	nids := make(map[int]map[*Rent591HomeDetailInfo]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(rent591homedetailinfo.Rent591homeDetailsTable)
		s.Join(joinT).On(s.C(rent591homedetail.FieldID), joinT.C(rent591homedetailinfo.Rent591homeDetailsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(rent591homedetailinfo.Rent591homeDetailsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(rent591homedetailinfo.Rent591homeDetailsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Rent591HomeDetailInfo]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Rent591HomeDetail](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "rent591home_details" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rdiq *Rent591HomeDetailInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rdiq.querySpec()
	_spec.Node.Columns = rdiq.ctx.Fields
	if len(rdiq.ctx.Fields) > 0 {
		_spec.Unique = rdiq.ctx.Unique != nil && *rdiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rdiq.driver, _spec)
}

func (rdiq *Rent591HomeDetailInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rent591homedetailinfo.Table, rent591homedetailinfo.Columns, sqlgraph.NewFieldSpec(rent591homedetailinfo.FieldID, field.TypeInt))
	_spec.From = rdiq.sql
	if unique := rdiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rdiq.path != nil {
		_spec.Unique = true
	}
	if fields := rdiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rent591homedetailinfo.FieldID)
		for i := range fields {
			if fields[i] != rent591homedetailinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rdiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rdiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rdiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rdiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rdiq *Rent591HomeDetailInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rdiq.driver.Dialect())
	t1 := builder.Table(rent591homedetailinfo.Table)
	columns := rdiq.ctx.Fields
	if len(columns) == 0 {
		columns = rent591homedetailinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rdiq.sql != nil {
		selector = rdiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rdiq.ctx.Unique != nil && *rdiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rdiq.predicates {
		p(selector)
	}
	for _, p := range rdiq.order {
		p(selector)
	}
	if offset := rdiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rdiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Rent591HomeDetailInfoGroupBy is the group-by builder for Rent591HomeDetailInfo entities.
type Rent591HomeDetailInfoGroupBy struct {
	selector
	build *Rent591HomeDetailInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rdigb *Rent591HomeDetailInfoGroupBy) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailInfoGroupBy {
	rdigb.fns = append(rdigb.fns, fns...)
	return rdigb
}

// Scan applies the selector query and scans the result into the given value.
func (rdigb *Rent591HomeDetailInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdigb.build.ctx, "GroupBy")
	if err := rdigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailInfoQuery, *Rent591HomeDetailInfoGroupBy](ctx, rdigb.build, rdigb, rdigb.build.inters, v)
}

func (rdigb *Rent591HomeDetailInfoGroupBy) sqlScan(ctx context.Context, root *Rent591HomeDetailInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rdigb.fns))
	for _, fn := range rdigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rdigb.flds)+len(rdigb.fns))
		for _, f := range *rdigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rdigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Rent591HomeDetailInfoSelect is the builder for selecting fields of Rent591HomeDetailInfo entities.
type Rent591HomeDetailInfoSelect struct {
	*Rent591HomeDetailInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rdis *Rent591HomeDetailInfoSelect) Aggregate(fns ...AggregateFunc) *Rent591HomeDetailInfoSelect {
	rdis.fns = append(rdis.fns, fns...)
	return rdis
}

// Scan applies the selector query and scans the result into the given value.
func (rdis *Rent591HomeDetailInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rdis.ctx, "Select")
	if err := rdis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeDetailInfoQuery, *Rent591HomeDetailInfoSelect](ctx, rdis.Rent591HomeDetailInfoQuery, rdis, rdis.inters, v)
}

func (rdis *Rent591HomeDetailInfoSelect) sqlScan(ctx context.Context, root *Rent591HomeDetailInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rdis.fns))
	for _, fn := range rdis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rdis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rdis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
