// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailpositionrounddatachildren"
)

// Rent591HomeDetailPositionRoundDataChildren is the model entity for the Rent591HomeDetailPositionRoundDataChildren schema.
type Rent591HomeDetailPositionRoundDataChildren struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Rent591HomeDetailPositionRoundDataChildrenQuery when eager-loading is set.
	Edges        Rent591HomeDetailPositionRoundDataChildrenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// Rent591HomeDetailPositionRoundDataChildrenEdges holds the relations/edges for other nodes in the graph.
type Rent591HomeDetailPositionRoundDataChildrenEdges struct {
	// Rent591homeDetailPositionRoundDatas holds the value of the rent591home_detail_position_round_datas edge.
	Rent591homeDetailPositionRoundDatas []*Rent591HomeDetailPositionRoundData `json:"rent591home_detail_position_round_datas,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// Rent591homeDetailPositionRoundDatasOrErr returns the Rent591homeDetailPositionRoundDatas value or an error if the edge
// was not loaded in eager-loading.
func (e Rent591HomeDetailPositionRoundDataChildrenEdges) Rent591homeDetailPositionRoundDatasOrErr() ([]*Rent591HomeDetailPositionRoundData, error) {
	if e.loadedTypes[0] {
		return e.Rent591homeDetailPositionRoundDatas, nil
	}
	return nil, &NotLoadedError{edge: "rent591home_detail_position_round_datas"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Rent591HomeDetailPositionRoundDataChildren) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rent591homedetailpositionrounddatachildren.FieldID:
			values[i] = new(sql.NullInt64)
		case rent591homedetailpositionrounddatachildren.FieldName, rent591homedetailpositionrounddatachildren.FieldKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Rent591HomeDetailPositionRoundDataChildren fields.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rent591homedetailpositionrounddatachildren.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rdprdc.ID = int(value.Int64)
		case rent591homedetailpositionrounddatachildren.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				rdprdc.Name = value.String
			}
		case rent591homedetailpositionrounddatachildren.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				rdprdc.Key = value.String
			}
		default:
			rdprdc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Rent591HomeDetailPositionRoundDataChildren.
// This includes values selected through modifiers, order, etc.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) Value(name string) (ent.Value, error) {
	return rdprdc.selectValues.Get(name)
}

// QueryRent591homeDetailPositionRoundDatas queries the "rent591home_detail_position_round_datas" edge of the Rent591HomeDetailPositionRoundDataChildren entity.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) QueryRent591homeDetailPositionRoundDatas() *Rent591HomeDetailPositionRoundDataQuery {
	return NewRent591HomeDetailPositionRoundDataChildrenClient(rdprdc.config).QueryRent591homeDetailPositionRoundDatas(rdprdc)
}

// Update returns a builder for updating this Rent591HomeDetailPositionRoundDataChildren.
// Note that you need to call Rent591HomeDetailPositionRoundDataChildren.Unwrap() before calling this method if this Rent591HomeDetailPositionRoundDataChildren
// was returned from a transaction, and the transaction was committed or rolled back.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) Update() *Rent591HomeDetailPositionRoundDataChildrenUpdateOne {
	return NewRent591HomeDetailPositionRoundDataChildrenClient(rdprdc.config).UpdateOne(rdprdc)
}

// Unwrap unwraps the Rent591HomeDetailPositionRoundDataChildren entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) Unwrap() *Rent591HomeDetailPositionRoundDataChildren {
	_tx, ok := rdprdc.config.driver.(*txDriver)
	if !ok {
		panic("ent: Rent591HomeDetailPositionRoundDataChildren is not a transactional entity")
	}
	rdprdc.config.driver = _tx.drv
	return rdprdc
}

// String implements the fmt.Stringer.
func (rdprdc *Rent591HomeDetailPositionRoundDataChildren) String() string {
	var builder strings.Builder
	builder.WriteString("Rent591HomeDetailPositionRoundDataChildren(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rdprdc.ID))
	builder.WriteString("name=")
	builder.WriteString(rdprdc.Name)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(rdprdc.Key)
	builder.WriteByte(')')
	return builder.String()
}

// Rent591HomeDetailPositionRoundDataChildrens is a parsable slice of Rent591HomeDetailPositionRoundDataChildren.
type Rent591HomeDetailPositionRoundDataChildrens []*Rent591HomeDetailPositionRoundDataChildren
