// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591home"
	"github.com/programzheng/rent-house-crawler/ent/rent591hometag"
)

// Rent591HomeTagQuery is the builder for querying Rent591HomeTag entities.
type Rent591HomeTagQuery struct {
	config
	ctx              *QueryContext
	order            []rent591hometag.OrderOption
	inters           []Interceptor
	predicates       []predicate.Rent591HomeTag
	withRent591homes *Rent591HomeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Rent591HomeTagQuery builder.
func (rtq *Rent591HomeTagQuery) Where(ps ...predicate.Rent591HomeTag) *Rent591HomeTagQuery {
	rtq.predicates = append(rtq.predicates, ps...)
	return rtq
}

// Limit the number of records to be returned by this query.
func (rtq *Rent591HomeTagQuery) Limit(limit int) *Rent591HomeTagQuery {
	rtq.ctx.Limit = &limit
	return rtq
}

// Offset to start from.
func (rtq *Rent591HomeTagQuery) Offset(offset int) *Rent591HomeTagQuery {
	rtq.ctx.Offset = &offset
	return rtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rtq *Rent591HomeTagQuery) Unique(unique bool) *Rent591HomeTagQuery {
	rtq.ctx.Unique = &unique
	return rtq
}

// Order specifies how the records should be ordered.
func (rtq *Rent591HomeTagQuery) Order(o ...rent591hometag.OrderOption) *Rent591HomeTagQuery {
	rtq.order = append(rtq.order, o...)
	return rtq
}

// QueryRent591homes chains the current query on the "rent591homes" edge.
func (rtq *Rent591HomeTagQuery) QueryRent591homes() *Rent591HomeQuery {
	query := (&Rent591HomeClient{config: rtq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(rent591hometag.Table, rent591hometag.FieldID, selector),
			sqlgraph.To(rent591home.Table, rent591home.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, rent591hometag.Rent591homesTable, rent591hometag.Rent591homesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(rtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Rent591HomeTag entity from the query.
// Returns a *NotFoundError when no Rent591HomeTag was found.
func (rtq *Rent591HomeTagQuery) First(ctx context.Context) (*Rent591HomeTag, error) {
	nodes, err := rtq.Limit(1).All(setContextOp(ctx, rtq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{rent591hometag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) FirstX(ctx context.Context) *Rent591HomeTag {
	node, err := rtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Rent591HomeTag ID from the query.
// Returns a *NotFoundError when no Rent591HomeTag ID was found.
func (rtq *Rent591HomeTagQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtq.Limit(1).IDs(setContextOp(ctx, rtq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{rent591hometag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) FirstIDX(ctx context.Context) int {
	id, err := rtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Rent591HomeTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Rent591HomeTag entity is found.
// Returns a *NotFoundError when no Rent591HomeTag entities are found.
func (rtq *Rent591HomeTagQuery) Only(ctx context.Context) (*Rent591HomeTag, error) {
	nodes, err := rtq.Limit(2).All(setContextOp(ctx, rtq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{rent591hometag.Label}
	default:
		return nil, &NotSingularError{rent591hometag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) OnlyX(ctx context.Context) *Rent591HomeTag {
	node, err := rtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Rent591HomeTag ID in the query.
// Returns a *NotSingularError when more than one Rent591HomeTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (rtq *Rent591HomeTagQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rtq.Limit(2).IDs(setContextOp(ctx, rtq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{rent591hometag.Label}
	default:
		err = &NotSingularError{rent591hometag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) OnlyIDX(ctx context.Context) int {
	id, err := rtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Rent591HomeTags.
func (rtq *Rent591HomeTagQuery) All(ctx context.Context) ([]*Rent591HomeTag, error) {
	ctx = setContextOp(ctx, rtq.ctx, "All")
	if err := rtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Rent591HomeTag, *Rent591HomeTagQuery]()
	return withInterceptors[[]*Rent591HomeTag](ctx, rtq, qr, rtq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) AllX(ctx context.Context) []*Rent591HomeTag {
	nodes, err := rtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Rent591HomeTag IDs.
func (rtq *Rent591HomeTagQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rtq.ctx.Unique == nil && rtq.path != nil {
		rtq.Unique(true)
	}
	ctx = setContextOp(ctx, rtq.ctx, "IDs")
	if err = rtq.Select(rent591hometag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) IDsX(ctx context.Context) []int {
	ids, err := rtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rtq *Rent591HomeTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rtq.ctx, "Count")
	if err := rtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rtq, querierCount[*Rent591HomeTagQuery](), rtq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) CountX(ctx context.Context) int {
	count, err := rtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rtq *Rent591HomeTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rtq.ctx, "Exist")
	switch _, err := rtq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rtq *Rent591HomeTagQuery) ExistX(ctx context.Context) bool {
	exist, err := rtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Rent591HomeTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rtq *Rent591HomeTagQuery) Clone() *Rent591HomeTagQuery {
	if rtq == nil {
		return nil
	}
	return &Rent591HomeTagQuery{
		config:           rtq.config,
		ctx:              rtq.ctx.Clone(),
		order:            append([]rent591hometag.OrderOption{}, rtq.order...),
		inters:           append([]Interceptor{}, rtq.inters...),
		predicates:       append([]predicate.Rent591HomeTag{}, rtq.predicates...),
		withRent591homes: rtq.withRent591homes.Clone(),
		// clone intermediate query.
		sql:  rtq.sql.Clone(),
		path: rtq.path,
	}
}

// WithRent591homes tells the query-builder to eager-load the nodes that are connected to
// the "rent591homes" edge. The optional arguments are used to configure the query builder of the edge.
func (rtq *Rent591HomeTagQuery) WithRent591homes(opts ...func(*Rent591HomeQuery)) *Rent591HomeTagQuery {
	query := (&Rent591HomeClient{config: rtq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rtq.withRent591homes = query
	return rtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Rent591HomeTag.Query().
//		GroupBy(rent591hometag.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rtq *Rent591HomeTagQuery) GroupBy(field string, fields ...string) *Rent591HomeTagGroupBy {
	rtq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Rent591HomeTagGroupBy{build: rtq}
	grbuild.flds = &rtq.ctx.Fields
	grbuild.label = rent591hometag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Rent591HomeTag.Query().
//		Select(rent591hometag.FieldName).
//		Scan(ctx, &v)
func (rtq *Rent591HomeTagQuery) Select(fields ...string) *Rent591HomeTagSelect {
	rtq.ctx.Fields = append(rtq.ctx.Fields, fields...)
	sbuild := &Rent591HomeTagSelect{Rent591HomeTagQuery: rtq}
	sbuild.label = rent591hometag.Label
	sbuild.flds, sbuild.scan = &rtq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Rent591HomeTagSelect configured with the given aggregations.
func (rtq *Rent591HomeTagQuery) Aggregate(fns ...AggregateFunc) *Rent591HomeTagSelect {
	return rtq.Select().Aggregate(fns...)
}

func (rtq *Rent591HomeTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rtq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rtq); err != nil {
				return err
			}
		}
	}
	for _, f := range rtq.ctx.Fields {
		if !rent591hometag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rtq.path != nil {
		prev, err := rtq.path(ctx)
		if err != nil {
			return err
		}
		rtq.sql = prev
	}
	return nil
}

func (rtq *Rent591HomeTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Rent591HomeTag, error) {
	var (
		nodes       = []*Rent591HomeTag{}
		_spec       = rtq.querySpec()
		loadedTypes = [1]bool{
			rtq.withRent591homes != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Rent591HomeTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Rent591HomeTag{config: rtq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rtq.withRent591homes; query != nil {
		if err := rtq.loadRent591homes(ctx, query, nodes,
			func(n *Rent591HomeTag) { n.Edges.Rent591homes = []*Rent591Home{} },
			func(n *Rent591HomeTag, e *Rent591Home) { n.Edges.Rent591homes = append(n.Edges.Rent591homes, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rtq *Rent591HomeTagQuery) loadRent591homes(ctx context.Context, query *Rent591HomeQuery, nodes []*Rent591HomeTag, init func(*Rent591HomeTag), assign func(*Rent591HomeTag, *Rent591Home)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Rent591HomeTag)
	nids := make(map[int]map[*Rent591HomeTag]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(rent591hometag.Rent591homesTable)
		s.Join(joinT).On(s.C(rent591home.FieldID), joinT.C(rent591hometag.Rent591homesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(rent591hometag.Rent591homesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(rent591hometag.Rent591homesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Rent591HomeTag]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Rent591Home](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "rent591homes" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (rtq *Rent591HomeTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rtq.querySpec()
	_spec.Node.Columns = rtq.ctx.Fields
	if len(rtq.ctx.Fields) > 0 {
		_spec.Unique = rtq.ctx.Unique != nil && *rtq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rtq.driver, _spec)
}

func (rtq *Rent591HomeTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(rent591hometag.Table, rent591hometag.Columns, sqlgraph.NewFieldSpec(rent591hometag.FieldID, field.TypeInt))
	_spec.From = rtq.sql
	if unique := rtq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rtq.path != nil {
		_spec.Unique = true
	}
	if fields := rtq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rent591hometag.FieldID)
		for i := range fields {
			if fields[i] != rent591hometag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rtq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rtq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rtq *Rent591HomeTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rtq.driver.Dialect())
	t1 := builder.Table(rent591hometag.Table)
	columns := rtq.ctx.Fields
	if len(columns) == 0 {
		columns = rent591hometag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rtq.sql != nil {
		selector = rtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rtq.ctx.Unique != nil && *rtq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rtq.predicates {
		p(selector)
	}
	for _, p := range rtq.order {
		p(selector)
	}
	if offset := rtq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rtq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Rent591HomeTagGroupBy is the group-by builder for Rent591HomeTag entities.
type Rent591HomeTagGroupBy struct {
	selector
	build *Rent591HomeTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rtgb *Rent591HomeTagGroupBy) Aggregate(fns ...AggregateFunc) *Rent591HomeTagGroupBy {
	rtgb.fns = append(rtgb.fns, fns...)
	return rtgb
}

// Scan applies the selector query and scans the result into the given value.
func (rtgb *Rent591HomeTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rtgb.build.ctx, "GroupBy")
	if err := rtgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeTagQuery, *Rent591HomeTagGroupBy](ctx, rtgb.build, rtgb, rtgb.build.inters, v)
}

func (rtgb *Rent591HomeTagGroupBy) sqlScan(ctx context.Context, root *Rent591HomeTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rtgb.fns))
	for _, fn := range rtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rtgb.flds)+len(rtgb.fns))
		for _, f := range *rtgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rtgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rtgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Rent591HomeTagSelect is the builder for selecting fields of Rent591HomeTag entities.
type Rent591HomeTagSelect struct {
	*Rent591HomeTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rts *Rent591HomeTagSelect) Aggregate(fns ...AggregateFunc) *Rent591HomeTagSelect {
	rts.fns = append(rts.fns, fns...)
	return rts
}

// Scan applies the selector query and scans the result into the given value.
func (rts *Rent591HomeTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rts.ctx, "Select")
	if err := rts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Rent591HomeTagQuery, *Rent591HomeTagSelect](ctx, rts.Rent591HomeTagQuery, rts, rts.inters, v)
}

func (rts *Rent591HomeTagSelect) sqlScan(ctx context.Context, root *Rent591HomeTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rts.fns))
	for _, fn := range rts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
