// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/programzheng/rent-house-crawler/ent/predicate"
	"github.com/programzheng/rent-house-crawler/ent/rent591homedetailinfo"
)

// Rent591HomeDetailInfoDelete is the builder for deleting a Rent591HomeDetailInfo entity.
type Rent591HomeDetailInfoDelete struct {
	config
	hooks    []Hook
	mutation *Rent591HomeDetailInfoMutation
}

// Where appends a list predicates to the Rent591HomeDetailInfoDelete builder.
func (rdid *Rent591HomeDetailInfoDelete) Where(ps ...predicate.Rent591HomeDetailInfo) *Rent591HomeDetailInfoDelete {
	rdid.mutation.Where(ps...)
	return rdid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rdid *Rent591HomeDetailInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rdid.sqlExec, rdid.mutation, rdid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rdid *Rent591HomeDetailInfoDelete) ExecX(ctx context.Context) int {
	n, err := rdid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rdid *Rent591HomeDetailInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rent591homedetailinfo.Table, sqlgraph.NewFieldSpec(rent591homedetailinfo.FieldID, field.TypeInt))
	if ps := rdid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rdid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rdid.mutation.done = true
	return affected, err
}

// Rent591HomeDetailInfoDeleteOne is the builder for deleting a single Rent591HomeDetailInfo entity.
type Rent591HomeDetailInfoDeleteOne struct {
	rdid *Rent591HomeDetailInfoDelete
}

// Where appends a list predicates to the Rent591HomeDetailInfoDelete builder.
func (rdido *Rent591HomeDetailInfoDeleteOne) Where(ps ...predicate.Rent591HomeDetailInfo) *Rent591HomeDetailInfoDeleteOne {
	rdido.rdid.mutation.Where(ps...)
	return rdido
}

// Exec executes the deletion query.
func (rdido *Rent591HomeDetailInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := rdido.rdid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rent591homedetailinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rdido *Rent591HomeDetailInfoDeleteOne) ExecX(ctx context.Context) {
	if err := rdido.Exec(ctx); err != nil {
		panic(err)
	}
}
