name: Build and Test

on:
  push:
    branches:
      - main
jobs:
  lint:
    strategy:
      matrix:
        go-version: ['>=1.21.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '${{ matrix.go-version }}'
    
    - name: Check out code
      uses: actions/checkout@v3

    # - name: Testing
    #   run: |
    #     go test -v ./...

    - name: Build binary
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o release/linux/amd64/rent-house-crawler ./main.go

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile.linux
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rent-house-crawler:latest

    - name: Update the API server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          docker compose pull
          docker compose up -d